name: random_string_one
description: A package which allows for modular control over random string generation with a single function.
version: 1.0.2
author: Jonas Zebari <jonaszebari@gmail.com>
homepage: https://github.com/jonas-zebari/random_string

environment:
  sdk: ">=2.2.2<3.0.0"
