name: random_string
description: A package which allows for modular control over random string generation.
version: 1.0.0
author: Jonas Zebari <jonaszebari@gmail.com>
homepage: https://github.com/jonas-zebari/random_string

environment:
  sdk: ">=2.2.2<3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
